#!/usr/bin/env python
import sys, re
from subprocess import check_output

commit_msg_filepath = sys.argv[1]

branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip().decode('utf-8')
regex = r'(\w+\d+)([ -_A-Za-z0-9]+)'

with open(commit_msg_filepath, 'r+') as fh:
    commit_msg = fh.read()
    # (OPT) Body
    if re.match(regex, branch):
        ticket = re.match(regex, branch).group(1)
        fh.seek(0, 0)
        fh.write(f'[{ticket}]\n')
    # https://www.conventionalcommits.org/en/v1.0.0/
    # Type: fix, feat, build, chore, ci, docs, style, refactor, perf, test
    fh.write('Type = fix/feat/build/chore/ci/docs/style/refactor/perf/test:\t\n')
    fh.write(f'{commit_msg}')
    # (OPT) Footer: Breaking change
    # fh.write('(opt) footer:\t\n')

            


