#!/usr/bin/env python
import sys, re
from subprocess import check_output

commit_msg_filepath = sys.argv[1]

branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip()
regex = '(\w+[ -_]?\d+)[ -_]?([A-Za-z_- 0-9]+)'
if re.match(regex, branch):
    ticket = re.match(regex, branch).group(1)
    with open(commit_msg_filepath, 'r+') as fh:
        commit_msg = fh.read()
        fh.seek(0, 0)
        fh.write('[%s] %s' % (ticket, commit_msg))
elif branch != 'main':
    print('Incorrect branch name')
    sys.exit(1)